backend:
  name: github
  repo: yochem/abel
  branch: main
media_folder: static/media
public_folder: /media
collections:
  - name: publicaties
    label: Publicaties
    label_singular: Publicatie
    folder: content/publicaties
    create: true
    editor:
      preview: false
    fields:
      - label: Paginanaam
        name: slug
        widget: string
        pattern: ['[a-z0-9_-]+', 'Toegestaan: a-z, 0-9, _ en -']
        hint: |
          De paginanaam in de URL:
          abelvanoosterwijk.com/publicaties/{{ paginanaam }}/.
      - label: Titel van artikel
        name: title
        widget: string
        hint: Je kan `*italics*` en `**bold**` gebruiken.
      - label: Ondertitel van artikel
        name: summary
        widget: string
        required: false
        hint: Je kan `*italics*` en `**bold**` gebruiken.
      - label: Publicatiedatum
        name: date
        widget: datetime
      - label: Verberg op website
        name: draft
        widget: boolean
        default: false
      - label: URL naar artikel
        name: link
        widget: string
        required: false
        hint: |
          Link naar het artikel op een andere website. Laat leeg voor een
          artikel op deze website.
      - label: Tekst van artikel
        name: body
        widget: markdown
        required: false
        hint: De tekst voor een artikel op deze website. Mag leeg blijven.
